##
## Two functions "makeCacheMatrix" and "cacheSolve" works together to efficiently calculate
## an inverse of a matrix by caching results of previous calculations.
##
## makeCacheMatrix creates a special object (list) which contains functions to retreive original matrix,
## to set a new matrix, to get the inverse matrix and to set the inverse matrix.
##
## cacheSolve uses standard solve() function to calculate inverse of a matrix. It uses an object, returned
## by makeCacheMatrix, to cache calculated inverse of a matrix to decrease running time.
## 


## makeCacheMatrix gets a matrix as an argument and returns a list of functions to retreive original matrix,
## to set a new matrix, to get the inverse matrix and to set the inverse matrix.

makeCacheMatrix <- function(x = matrix()) 
{
      ## until initialisation with "setinverse" method, inverted matrix shall be NULL
      inverse <- NULL 
      
      ## set function sets new matrix for this object and switch inverted matrix back to NULL until initialisation
      set <- function(y) 
      {
            x <<- y
            inverse <<- NULL
      }
      
      ## get function returns an associated matrix
      get <- function() 
      {
            x
      }
      
      
      ## setinverse function sets an inverse for the matrix
      setinverse <- function(inv) 
      {
            inverse <<- inv
      }

      ## getinverse function returns an inverse of the matrix.
      ## It shall be NULL until initialisation with "setinverse".
      getinverse <- function() 
      {      
            inverse
      }
      
      ## return a list, containing functions to work with data
      list(set = set, 
           get = get,
           setinverse = setinverse,
           getinverse = getinverse)
}

## cacheSolve gets a list, generated by makeCacheMatrix, and returns an inverse of the stored matrix.
## If an inverse for this matrix was calculated before, returns cached inverse.

cacheSolve <- function(x, ...) 
{
      ## try to get cached inverted matrix and check whether it was already initialised or not
      m <- x$getinverse()
      
      ## if initialised, return cached value
      if(!is.null(m)) {
            return(m)
      }
      
      ## Cached inverse was not initialised. Get original matrix
      data <- x$get()
      
      ## Calculate inverted matrix using solve()
      m <- solve(data, ...)
      
      ## Store calculated inverted matrix in the cache (initialise cache)
      x$setinverse(m)
      
      ## Return inverted matrix
      m
}

